// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type SensorDatum struct {
	ID          uint64       `json:"id"`
	SensorValue float64      `json:"sensor_value"`
	SensorType  string       `json:"sensor_type"`
	Id1         string       `json:"id1"`
	Id2         int32        `json:"id2"`
	Timestamp   time.Time    `json:"timestamp"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}
