// Code generated by MockGen. DO NOT EDIT.
// Source: ./sensor_service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	request "service-b/internal/dto/request"
	sqlc "service-b/internal/repository/mysql"

	gomock "github.com/golang/mock/gomock"
)

// MockISensorService is a mock of ISensorService interface.
type MockISensorService struct {
	ctrl     *gomock.Controller
	recorder *MockISensorServiceMockRecorder
}

// MockISensorServiceMockRecorder is the mock recorder for MockISensorService.
type MockISensorServiceMockRecorder struct {
	mock *MockISensorService
}

// NewMockISensorService creates a new mock instance.
func NewMockISensorService(ctrl *gomock.Controller) *MockISensorService {
	mock := &MockISensorService{ctrl: ctrl}
	mock.recorder = &MockISensorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISensorService) EXPECT() *MockISensorServiceMockRecorder {
	return m.recorder
}

// GetSensorByDevice mocks base method.
func (m *MockISensorService) GetSensorByDevice(ctx context.Context, params *request.GetSensorByDeviceRequest) ([]*sqlc.SensorDatum, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSensorByDevice", ctx, params)
	ret0, _ := ret[0].([]*sqlc.SensorDatum)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSensorByDevice indicates an expected call of GetSensorByDevice.
func (mr *MockISensorServiceMockRecorder) GetSensorByDevice(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSensorByDevice", reflect.TypeOf((*MockISensorService)(nil).GetSensorByDevice), ctx, params)
}
