version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: "@vincentweilasto16"
#       MYSQL_DATABASE: sensor_db
#       MYSQL_USER: root
#       MYSQL_PASSWORD: "@vincentweilasto16"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 10

#   sensor-platform-service-b:
#     build:
#       context: .
#       dockerfile: Dockerfile.http
#     container_name: sensor-platform-service-b
#     depends_on:
#       - kafka
#       - mysql
#     environment:
#       DB_HOST: mysql
#       DB_PORT: 3306
#       DB_USER: root
#       DB_PASSWORD: "@vincentweilasto16"
#       DB_NAME: sensor_db
#       KAFKA_BROKER: kafka:9092
#     ports:
#       - "8080:8080"

# volumes:
#   mysql_data: